spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
---
spring:
  profiles:
    active: dev
  h2.console.enabled: true
  datasource:
    platform: h2
    initialize: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:./tmp/h2;AUTO_SERVER=TRUE;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true
    properties.hibernate.format_sql: true
logging:
  level:
    com.eglowc.simpleblog: DEBUG
---
spring:
  profiles:
    active: pgql
  datasource:
    platform: postgresql
    initialize: true
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/simpleblog
    username: HCLEE
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties.hibernate.format_sql: true
logging:
  level:
    com.eglowc.simpleblog: DEBUG
    root: INFO
    org:
      springframework.web: ERROR
      hibernate: ERROR