spring:
  profiles:
    active: dev
  h2.console.enabled: true
  datasource:
    platform: h2
    initialize: true
    driverClassName: org.h2.Driver
    url: jdbc:h2:./tmp/h2;AUTO_SERVER=TRUE;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: h2
    show-sql: true
    properties.hibernate.format_sql: true
logging:
  level:
    com.eglowc.simpleblog: DEBUG